### ISSUE TITLE
Password is invalid when installing the certificate on iOS…

### ISSUE THREAD

**Issue by Chilip2022** [gunnarhaslinger/SMIME-OpenSSL-CA#1]

**Comment by Chilip2022** [comment]
password works great with Thunderbird…

**Comment by gunnarhaslinger** [comment]
Is it a current iOS-Version 16?
I would hope Apple finally updated their Crypto-Libraries these days to support modern AES/SHA256 with P12/PFX.

As I just googled: In the past they didn't.

This solution uses openssl v3 which uses modern AES/SHA256 when generating P12/PFX.
You can check the used Encryption of a P12 File as follows:

```console
CA> ..\openssl\openssl.exe pkcs12 -in certs\test.p12 -info
Enter Import Password:
MAC: sha256, Iteration 2048
MAC length: 32, salt length: 8
PKCS7 Encrypted data: PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
Certificate bag
...
```

You can try following: in "create_SMIME-Certificate.bat" you find following line:
```console
%openssl% pkcs12 -export -in "certs/%USER%.cer" -inkey "certs/%USER%.key" -chain -CAfile "ca-cert.cer" -name "%USER%" -passout pass:%PASSWORD% -out "certs/%USER%.p12"
```

Add those two additional Arguments: "-legacy -provider-path ..\openssl"
```console
%openssl% pkcs12 -export -in "certs/%USER%.cer" -inkey "certs/%USER%.key" -chain -CAfile "ca-cert.cer" -name "%USER%" -passout pass:%PASSWORD% -out "certs/%USER%.p12" -legacy -provider-path ..\openssl
```

If you analyse the "-legacy" generated P12 you find out it is encrypted weak "pbeWithSHA1And40BitRC2-CBC" now:
```console
CA>..\openssl\openssl.exe pkcs12 -in "certs\Richard John Doe.p12" -info -legacy -provider-path ..\openssl
Enter Import Password:
MAC: sha1, Iteration 2048
MAC length: 20, salt length: 8
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
```

=> And I guess this weak p12 would work on iPhone / iOS

**Comment by Chilip2022** [comment]
Great, it work‘s perfect!
Thank‘s a lot.

**Comment by gunnarhaslinger** [comment]
I updated the Package.
You can now just set `LEGACY_P12=YES` to get legacy Style P12 Files.
