### ISSUE TITLE
Export public key in pem for iOS

### ISSUE THREAD

**Issue by Chilip2022** [gunnarhaslinger/SMIME-OpenSSL-CA#2]
Do you have any idea how I can also save the public key in a pem file in order to distribute it to all iOS devices via MobileDeviceManagement?

Such as: 
%openssl% pkcs12 -in "certs/%USER%.p12" -clcerts -nokeys -out "pem/%USER%.pem"

**Comment by gunnarhaslinger** [comment]
Not sure what you like to get. You like to have a PEM or a PKCS12 = P12/PFX? 

What do you mean with "public key"? Only the public key without certificate or the full certificate but without private key? As all sorts of file already get generated I'm not sure what exactly you are asking about and like to achieve.

**Comment by gunnarhaslinger** [comment]
So best guess you are looking for the cer files in the certs folder. Those are the PEM certificate files of the users without private keys.

**Comment by Chilip2022** [comment]
I need exactly the information that is sent with an email so that encryption is possible. That's the whole certificate with no private key, right? In iOS, you first have to click on the sender and install the encryption certificate (without the private key). Only then is encryption possible. I would like to pass this on via MDM so that this process is not extra necessary. I tried the cer file, but that didn't work. I think iOS wants a PEM file...

**Comment by gunnarhaslinger** [comment]
The cer files are the PEM Files.

Yes, to encrypt mails you need the recipients Certificates (without private keys). The cer Files provided are exactly for this use case 

PEM means it is base64 encoded.

Other option would be binary / DER Format. But that's not PEM then. Maybe your deployment likes to see Binary/DER Format? If you have a working example just look inside if it is base64 encoded or binary

**Comment by Chilip2022** [comment]
Thank you. Hm, okay maybe i should try the Binary/DER Format. How can i create this? Thanks a lot for your support!!!

**Comment by gunnarhaslinger** [comment]
`openssl x509 -in "certs/%USER%.cer"  -out "certs/%USER%.der.cer" -outform DER`

**Comment by gunnarhaslinger** [comment]
@Chilip2022  You succeeded?

**Comment by Chilip2022** [comment]
It's not the certificate. The cer certificate that the script generates is great. The problem is iOS. Due to Apple restrictions, you cannot distribute public certificates to the iPads via MDM...
