### ISSUE TITLE
S/MiME not working on ios nor android 

### ISSUE THREAD

**Issue by ELIOX89** [gunnarhaslinger/SMIME-OpenSSL-CA#3]
hello,

hope you are doing well.

the certificate is working in outlook and thunderbird but unfortunately  not working on IOS can you please advise

it always send unable to sign

Regards,
 EN.

**Comment by gunnarhaslinger** [comment]
You are asking for a compatibility-feature which is already described as:

> If you need a working P12 for iPhone with old legacy Encryption you can set LEGACY_P12=YES, reason for this see #1 

In the Scripts you find this comment:
> OpenSSL v3 creates P12 Files using modern PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
> Some Legacy Devices like iPhones cannot handle this modern encryption but expect to get old pbeWithSHA1And40BitRC2-CBC
> If the P12 File should be created using pbeWithSHA1And40BitRC2-CBC (for compatibility with iPhone iOS) set LEGACY_P12=YES

so just change
`set LEGACY_P12=NO`
to
`set LEGACY_P12=YES`

**Comment by ELIOX89** [comment]
Sent from my iPhone

On 4 Oct 2023, at 17:05, Gunnar Haslinger ***@***.***> wrote:

﻿

You are asking for a compatibility-feature which is already descripted as:

If you need a working P12 for iPhone with old legacy Encryption you can set LEGACY_P12=YES, reason for this see #1<https://github.com/gunnarhaslinger/SMIME-OpenSSL-CA/issues/1>

In the Scripts you find this comment:

OpenSSL v3 creates P12 Files using modern PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
Some Legacy Devices like iPhones cannot handle this modern encryption but expect to get old pbeWithSHA1And40BitRC2-CBC
If the P12 File should be created using pbeWithSHA1And40BitRC2-CBC (for compatibility with iPhone iOS) set LEGACY_P12=YES

so just change
set LEGACY_P12=NO
to
set LEGACY_P12=YES

**Comment by ELIOX89** [comment]
Dear gunnarhaslinger,

First of all thank you for your swift response.

I did indeed enable the legacy and the certicate is already being used to sign on my iphone however i keep getting this error  so if you could help it would be great .
[image0.png]

**Comment by gunnarhaslinger** [comment]
I have no Idea what image you are referencing to.

**Comment by ELIOX89** [comment]
Dear gunnarhaslinger,

Below is the image of the error it seems that it won’t let me use the certificate to sign the email
It is workine fine on outlook and thunderbird

I just want to know if i am doind something wrong
Because already in the document you said to set to yes and it should work

That is why i asked you
[image0.png]

**Comment by gunnarhaslinger** [comment]
It seems you are not aware of how to use GitHub Issues.
Please read the Github-Manual how to upload an image: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by ELIOX89** [comment]
Dear Gunnar
i am sorry,  i was sending it via email below are the pictures

![picture 1](https://github.com/gunnarhaslinger/SMIME-OpenSSL-CA/assets/146957700/f1de363b-026f-435b-8885-41026c53b631)
![picture 2](https://github.com/gunnarhaslinger/SMIME-OpenSSL-CA/assets/146957700/6f2c05a8-63d6-4e31-9084-04e758aed128)
![picture 3](https://github.com/gunnarhaslinger/SMIME-OpenSSL-CA/assets/146957700/19485c2f-7a88-4b1d-9822-217c372d8bdf)

Appreciate your help!
Regards,
EN

**Comment by gunnarhaslinger** [comment]
I guess you didn't include your email-Address exactly spelled as configured as Subject-Alternative-Name into the certificate.

**Comment by ELIOX89** [comment]
i tested the two bat files and both of them are not working if there is something wrong that i am doing would you mind checking it?

```
rem ### Configuration ####################################
rem # USER = Certificate Common Name, e.g. First-Name Last-Name
rem # EMAIL = the E-Mail address of this user which is used for S/MIME Mailing
rem # PASSWORD = The password for the P12-File, it protects the Users Certificate, User needs this Password for Importing the p12-File
rem #            Avoid special characters, only use alphanumeric passwords
rem #######################################################


rem # Configure
set USER=Elio Najem
set EMAIL=enajem@sabis.net
set PASSWORD=123456

rem OpenSSL v3 creates P12 Files using modern PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
rem Some Legacy Devices like iPhones cannot handle this modern encryption but expect to get old pbeWithSHA1And40BitRC2-CBC
rem If the P12 File should be created using pbeWithSHA1And40BitRC2-CBC (for compatibility with iPhone iOS) set LEGACY_P12=YES
rem set LEGACY_P12=YES
set LEGACY_P12=YES


rem # Generate
cmd.exe /c create_SMIME-Certificate.bat
```

```
------------------------------------------------------------------------------------------------------------------------------
@echo off
rem # Gunnar Haslinger, 16.07.2020, 
rem # Source at GitHub: https://github.com/gunnarhaslinger/SMIME-OpenSSL-CA
rem # Blog: https://hitco.at/blog
rem # Creates an SMIME-Certificate

rem ### Configuration ####################################

rem Usually this Script and Configuration doesn't need to be modified.
rem Instead: Modify your Attributes like Username, E-Mail-Adress in the 
rem File "create_SMIME-Certificate-for-User.bat" which calls this script

rem # USER = Certificate Common Name, e.g. First-Name Last-Name
if "%USER%"=="" set USER=Elio Najem

rem # EMAIL = the E-Mail address of this user which is used for S/MIME Mailing
if "%EMAIL%"=="" set EMAIL=enajem@sabis.net

rem # The password for the P12-File, it protects the Users Certificate, User needs this Password for Importing the p12-File
rem # Avoid special characters, only use alphanumeric passwords
if "%PASSWORD%"=="" set PASSWORD=123456

rem OpenSSL v3 creates P12 Files using modern PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
rem Some Legacy Devices like iPhones cannot handle this modern encryption but expect to get old pbeWithSHA1And40BitRC2-CBC
rem If the P12 File should be created using pbeWithSHA1And40BitRC2-CBC (for compatibility with iPhone iOS) set LEGACY_P12=YES
if "%LEGACY_P12%"=="" set LEGACY_P12=YES

rem --- End of Configuration, no modification / configuration needed below ---
```

**Comment by gunnarhaslinger** [comment]
> i tested the two bat files and both of them are not working

The scripts are of course working.
The certificate-attributes I prepared in the scripts are suitable for s/mime.

I have no iPhone to check, so I'm sorry I am not able to give detailed iPhone/iOS advice. But I know my Certificates are working for iPhone SMIME Signing because I got feedback it is working when used LEGACY_P12=YES. When not using LEGACY_P12 the import fails.

What shows up when you click on the (i) in advanced / signing here? Does it show up as trusted? What details are shown?
<img width="223" alt="2023-10-05 09_36_04-272791583-6f2c05a8-63d6-4e31-9084-04e758aed128" src="https://github.com/gunnarhaslinger/SMIME-OpenSSL-CA/assets/8940065/0837939f-246b-47b6-a92d-2414378129d5">

**Comment by ELIOX89** [comment]
![E](https://github.com/gunnarhaslinger/SMIME-OpenSSL-CA/assets/146957700/89769a24-b248-42f9-b6ad-e1d48439d856)
![EE](https://github.com/gunnarhaslinger/SMIME-OpenSSL-CA/assets/146957700/9d64e5eb-df9e-4fd7-a02b-fb88d3e3b619)
![EEE](https://github.com/gunnarhaslinger/SMIME-OpenSSL-CA/assets/146957700/43760ca2-4d89-4d00-8834-373abd90a69f)
![EEEE](https://github.com/gunnarhaslinger/SMIME-OpenSSL-CA/assets/146957700/87b13240-5a77-4177-94ac-e46035860d4f)
![1E](https://github.com/gunnarhaslinger/SMIME-OpenSSL-CA/assets/146957700/4f6984ff-1d3c-4f2d-930b-12c86560b362)

**Comment by gunnarhaslinger** [comment]
So for me this Certificate looks perfectly fine.
Seems to be an iPhone configuration/usage Issue then.

**Comment by ELIOX89** [comment]
can i ask a favor please

can you create a certificate for me to test it on my iphone 

Regards,
EN

**Comment by gunnarhaslinger** [comment]
No, sorry. I'm not doing support like this.
The certificate you created is pretty fine. You have to check your iPhone/iOS Configuration.

**Comment by ELIOX89** [comment]
Okay thank you for your help

**Comment by ELIOX89** [comment]
sry to disturb you gunnar but on android i am getting under verification chain building error

**Comment by gunnarhaslinger** [comment]
As there is no preinstalled S/MIME capable mailing app in android you have to be a little bit more precise. Which Android-Version? Which Mailing-App? What exactly is the problem? 

Best Guess: You didn't add the generated Root-CA-Zertificate (the File ca-cert.cer) to the Trusted-CA-Certificates User-Store. The "A-Private-Mail Certificate Authority" has to show up there.
