### ISSUE TITLE
Cert won't create

### ISSUE THREAD

**Issue by filippvl** [gunnarhaslinger/SMIME-OpenSSL-CA#4]
Hi, I have an issue where certificate won't generate, it says it does but nothing happens.
In CA folder where it should be, it generates just a .txt file with file password.

Can this be solved somehow?

EDIT:
There's couple of lines that say:
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.

**Comment by filippvl** [comment]
I was using older version...

**Comment by gunnarhaslinger** [comment]
I don't know which "older version" you used, but all ZIP-File Releases I published are working and nothing should be missing.

**Comment by filippvl** [comment]
For some reason it didn't work until I extracted and tried again from latest version 3.2.1
